baseurl = "http://onceupondata.com/"
relativeurls = false
languageCode = "en-us"
title = "Once Upon Data"
theme = "beautifulhugo"
googleAnalytics = "UA-102384456-1"
disqusShortname = "onceupondata"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[Author]
    stackoverflow = "users/6535741/omaymas"
    github = "OmaymaS"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/OmaymaS"

[params]
    description = ""
    rss = true
    comments = true

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

